/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.lab;

public class App {
    public static void main(String[] args) {
        ru.bsuedu.cad.lab.app.OrderAppClient.runDemo();
    }
}
