/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    war
    jacoco // Плагин Jacoco для покрытия тестами
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // Add Spring Context dependency
    implementation(libs.spring.context)
    
    // Add Jakarta Annotations API for @PostConstruct
    implementation(libs.jakarta.annotation.api)
    
    // Spring Data JPA and ORM
    implementation("org.springframework.data:spring-data-jpa:3.2.5")
    implementation("org.springframework:spring-orm:6.1.5")

    // Hibernate (JPA provider)
    implementation("org.hibernate.orm:hibernate-core:6.4.4.Final")

    // H2 Database
    runtimeOnly("com.h2database:h2:2.2.224")

    // HikariCP for DataSource
    implementation("com.zaxxer:HikariCP:5.1.0")

    // Jakarta Persistence API
    implementation("jakarta.persistence:jakarta.persistence-api:3.1.0")

    // Логирование
    implementation("org.slf4j:slf4j-api:2.0.13")
    runtimeOnly("ch.qos.logback:logback-classic:1.5.6")

    // Для поддержки сервлетов и интеграции со Spring Web
    providedCompile("jakarta.servlet:jakarta.servlet-api:6.1.0")
    implementation("org.springframework:spring-web:6.1.5")

    // Spring MVC
    implementation("org.springframework:spring-webmvc:6.1.5")
    // Jackson для JSON
    implementation("com.fasterxml.jackson.core:jackson-databind:2.17.0")
    // Thymeleaf
    implementation("org.thymeleaf:thymeleaf:3.1.2.RELEASE")
    implementation("org.thymeleaf:thymeleaf-spring6:3.1.2.RELEASE")
    // Jackson для поддержки Java 8 Date/Time API
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.0")

    // Spring Security
    implementation("org.springframework.security:spring-security-web:6.2.2")
    implementation("org.springframework.security:spring-security-config:6.2.2")

    // Thymeleaf Spring Security dialect
    implementation("org.thymeleaf.extras:thymeleaf-extras-springsecurity6:3.1.1.RELEASE")

    // Mockito для моков
    testImplementation("org.mockito:mockito-core:5.2.0")
    testImplementation("org.mockito:mockito-junit-jupiter:5.2.0")
    // AssertJ для удобных assert'ов
    testImplementation("org.assertj:assertj-core:3.25.3")

    // Spring Test для интеграционного тестирования
    testImplementation("org.springframework:spring-test:6.2.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    // Define the main class for the application.
    mainClass = "ru.bsuedu.cad.lab.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.withType<JavaCompile>().configureEach {
    options.encoding = "UTF-8"
    options.compilerArgs.add("-parameters")
}

tasks.withType<Javadoc>().configureEach {
    options.encoding = "UTF-8"
}

tasks.withType<JavaExec>().configureEach {
    standardInput = System.`in`
    standardOutput = System.out
    jvmArgs = listOf(
        "-Dfile.encoding=UTF-8", 
        "-Dconsole.encoding=UTF-8",
        "-Dsun.stdout.encoding=UTF-8",
        "-Dsun.stderr.encoding=UTF-8",
        "-Dspring.output.ansi.enabled=ALWAYS"
    )
    systemProperty("file.encoding", "UTF-8")
    systemProperty("console.encoding", "UTF-8")
}
