/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.lab;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import ru.bsuedu.cad.lab.config.AppConfig;
import ru.bsuedu.cad.lab.renderer.Renderer;

public class App {
    public static void main(String[] args) {
        // Создаем контекст Spring на основе конфигурации AppConfig.
        try (var ctx = new AnnotationConfigApplicationContext(AppConfig.class)) {
            // Получаем компонент Renderer из контейнера Spring.
            Renderer renderer = ctx.getBean(Renderer.class);
            // Вызываем метод render для вывода данных о продуктах.
            renderer.render();
        }
    }
}
