/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.lab;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import ru.bsuedu.cad.lab.config.AppConfig;
import ru.bsuedu.cad.lab.renderer.Renderer;

public class App {
    public static void main(String[] args) {
        System.out.println("Запуск приложения для домашнего магазина...");
        System.out.println("Рабочий каталог: " + System.getProperty("user.dir"));
        
        // Отладочный вывод аргументов
        System.out.println("Аргументы командной строки:");
        System.out.println("Количество аргументов: " + args.length);
        for (int i = 0; i < args.length; i++) {
            System.out.println("Аргумент " + i + ": '" + args[i] + "'");
        }
        
        // Обработка аргументов командной строки
        if (args.length > 0) {
            String rendererArg = args[0].toLowerCase();
            if ("--renderer".equals(rendererArg) && args.length > 1) {
                String rendererType = args[1].toLowerCase();
                AppConfig.setRendererType(rendererType);
                System.out.println("Использование рендерера: " + rendererType);
            } else if ("--help".equals(rendererArg) || "-h".equals(rendererArg)) {
                printUsage();
                return;
            } else {
                // Если передан просто тип рендерера без флага
                AppConfig.setRendererType(rendererArg);
                System.out.println("Использование рендерера: " + rendererArg);
            }
        }
        
        // Создаем контекст Spring на основе конфигурации AppConfig.
        try (var ctx = new AnnotationConfigApplicationContext(AppConfig.class)) {
            System.out.println("Контекст приложения инициализируется успешно.");
            
            // Получаем компонент Renderer из контейнера Spring.
            Renderer renderer = ctx.getBean(Renderer.class);
            System.out.println("Использование рендерера: " + renderer.getClass().getSimpleName());
            
            // Вызываем метод render для вывода данных о продуктах.
            renderer.render();
            
            System.out.println("Приложение успешно выполнено.");
        }
    }
    
    private static void printUsage() {
        System.out.println("Использование:");
        System.out.println("  gradlew clean run");
        System.out.println("  gradlew clean run --args=\"[console|html]\"");
        System.out.println();
        System.out.println("Аргументы:");
        System.out.println("  console   Использовать рендерер таблицы в консоль");
        System.out.println("  html      Использовать рендерер таблицы в HTML (по умолчанию)");
        System.out.println();
        System.out.println("Опции:");
        System.out.println("  --help, -h   Показать эту справку");
    }
}
