/*
 * This source file was generated by the Gradle 'init' task
 */
package ru.bsuedu.cad.lab;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import ru.bsuedu.cad.lab.config.AppConfig;
import ru.bsuedu.cad.lab.renderer.Renderer;
import ru.bsuedu.cad.lab.request.CategoryRequest;

public class App {
    public static void main(String[] args) {
        System.out.println("Запуск приложения для домашнего магазина...");
        System.out.println("Рабочий каталог: " + System.getProperty("user.dir"));
        
        // Отладочный вывод аргументов
        System.out.println("Аргументы командной строки:");
        System.out.println("Количество аргументов: " + args.length);
        for (int i = 0; i < args.length; i++) {
            System.out.println("Аргумент " + i + ": '" + args[i] + "'");
        }
        
        System.out.println("Аргументы при запуске: " + java.util.Arrays.toString(args));
        // Новый способ выбора рендерера
        String rendererType = "console"; // по умолчанию
        for (String arg : args) {
            String lower = arg.toLowerCase();
            if (lower.equals("console") || lower.equals("html") || lower.equals("db")) {
                rendererType = lower;
                break;
            }
        }
        System.out.println("rendererType до setRendererType: " + rendererType);
        AppConfig.setRendererType(rendererType);
        System.out.println("rendererType после setRendererType: " + rendererType);
        
        // Создаем контекст Spring на основе конфигурации AppConfig.
        try (var ctx = new AnnotationConfigApplicationContext(AppConfig.class)) {
            System.out.println("Контекст приложения инициализируется успешно.");
            
            // Получаем компонент Renderer из контейнера Spring.
            Renderer renderer = ctx.getBean(Renderer.class);
            System.out.println("Использование рендерера: " + renderer.getClass().getSimpleName());
            
            // Вызываем метод render для вывода данных о продуктах.
            renderer.render();
            
            // Логируем категории с количеством товаров больше единицы только если передан аргумент --log-categories или --log
            boolean logCategories = false;
            for (String arg : args) {
                if ("--log-categories".equalsIgnoreCase(arg) || "--log".equalsIgnoreCase(arg)) {
                    logCategories = true;
                    break;
                }
            }
            if (logCategories) {
                CategoryRequest categoryRequest = ctx.getBean(CategoryRequest.class);
                categoryRequest.logCategoriesWithMultipleProducts();
            }
            
            System.out.println("Приложение успешно выполнено.");
        }
    }
    
    private static void printUsage() {
        System.out.println("Использование:");
        System.out.println("  gradlew clean run");
        System.out.println("  gradlew clean run --args=\"[console|html|db] [--log-categories]\"");
        System.out.println();
        System.out.println("Аргументы:");
        System.out.println("  console   Использовать рендерер таблицы в консоль");
        System.out.println("  html      Использовать рендерер таблицы в HTML");
        System.out.println("  db        Использовать DataBaseRenderer (по умолчанию)");
        System.out.println();
        System.out.println("Опции:");
        System.out.println("  --log-categories, --log   Логировать категории с количеством товаров больше единицы");
        System.out.println("  --help, -h   Показать эту справку");
    }
}
